// <auto-generated />
using EpitmenyadoWebApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EpitmenyadoWebApp.Migrations
{
    [DbContext(typeof(EpitmenyadoDbContext))]
    partial class EpitmenyadoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("EpitmenyadoWebApp.Models.Epitmeny", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<char>("Adosav")
                        .HasColumnType("TEXT");

                    b.Property<int>("Alapterulet")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Hazszam")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Tulajdonos")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Utca")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Epitmenyek");
                });
#pragma warning restore 612, 618
        }
    }
}
